export const productData = [
	{
	  id: 1,
	  title: 'Nescafe Classic Instant Coffee Powder',
	  image: require('../../../../../assets/image.jpg'),
	  weight: '100g',
	  price: 10,
	  quantity: 10,
	},
	{
	  id: 2,
	  title: 'Tata Tea Agni Special Blend Tea',
	  image: require('../../../../../assets/image.jpg'),
	  weight: '200g',
	  price: 20,
	  quantity: 20,
	},
	{
	  id: 3,
	  title: 'Organic India Infusion Bags - Tulsi Green Tea',
	  image: require('../../../../../assets/Image2.png'),
	  weight: '300g',
	  price: 30,
	  quantity: 30,
	},
	{
	  id: 4,
	  title: 'Product 4',
	  image: require('../../../../../assets/Image2.png'),
	  weight: '300g',
	  price: 30,
	  quantity: 40,
	},
	{
	  id: 5,
	  title: 'Product 5',
	  image: require('../../../../../assets/Image2.png'),
	  weight: '300g',
	  price: 30,
	  quantity: 50,
	},
	{
	  id: 6,
	  title: 'Product 6',
	  image: require('../../../../../assets/Image2.png'),
	  weight: '300g',
	  price: 30,
	  quantity: 60,
	},
	{
	  id: 7,
	  title: 'Product 7',
	  image: require('../../../../../assets/Image2.png'),
	  weight: '300g',
	  price: 30,
	  quantity: 70,
	},
	{
	  id: 8,
	  title: 'Product 8',
	  image: require('../../../../../assets/Image2.png'),
	  weight: '300g',
	  price: 30,
	  quantity: 80,
	},
	{
	  id: 9,
	  title: 'Product 9',
	  image: require('../../../../../assets/Image2.png'),
	  weight: '300g',
	  price: 30,
	  quantity: 90,
	},
	// Add more products as needed
  ];