const dummyData = [
	{
	  id: 1,
	  name: 'Salon A',
	  pincode: '1234',
	  location: 'Location A',
	  deliveryAvailable: true,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: true,
	},
	{
	  id: 2,
	  name: 'Salon B',
	  pincode: '1234',
	  location: 'Location B',
	  deliveryAvailable: false,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: false,
	},
	{
	  id: 3,
	  name: 'Salon C',
	  pincode: '4321',
	  location: 'Location C',
	  deliveryAvailable: true,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: true,
	},
	{
	  id: 4,
	  name: 'Salon D',
	  pincode: '4321',
	  location: 'Location D',
	  deliveryAvailable: false,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: false,
	},
	{
	  id: 5,
	  name: 'Salon E',
	  pincode: '151',
	  location: 'Location E',
	  deliveryAvailable: true,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: true,
	},
	{
	  id: 6,
	  name: 'Salon F',
	  pincode: '151',
	  location: 'Location F',
	  deliveryAvailable: false,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: false,
	},
	{
	  id: 7,
	  name: 'Salon G',
	  pincode: '1234',
	  location: 'Location G',
	  deliveryAvailable: true,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: true,
	},
	{
	  id: 8,
	  name: 'Salon H',
	  pincode: '1234',
	  location: 'Location H',
	  deliveryAvailable: false,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: false,
	},
	{
	  id: 9,
	  name: 'Salon I',
	  pincode: '4321',
	  location: 'Location I',
	  deliveryAvailable: true,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: true,
	},
	{
	  id: 10,
	  name: 'Salon J',
	  pincode: '4321',
	  location: 'Location J',
	  deliveryAvailable: false,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: false,
	},
	{
	  id: 11,
	  name: 'Salon K',
	  pincode: '151',
	  location: 'Location K',
	  deliveryAvailable: true,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: true,
	},
	{
	  id: 12,
	  name: 'Salon L',
	  pincode: '151',
	  location: 'Location L',
	  deliveryAvailable: false,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: false,
	},
	{
	  id: 13,
	  name: 'Salon M',
	  pincode: '1234',
	  location: 'Location M',
	  deliveryAvailable: true,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: true,
	},
	{
	  id: 14,
	  name: 'Salon N',
	  pincode: '1234',
	  location: 'Location N',
	  deliveryAvailable: false,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: false,
	},
	{
	  id: 15,
	  name: 'Salon O',
	  pincode: '4321',
	  location: 'Location O',
	  deliveryAvailable: true,
	  image: require('../../../../assets/image.jpg'),
	  isOpen: true,
	},
  ];
  
  export default dummyData;
  